//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CammsEngine
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class cammsEntities : DbContext
    {
        public cammsEntities()
            : base("name=cammsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblStockMovementType> tblStockMovementTypes { get; set; }
        public virtual DbSet<tblFuel> tblFuels { get; set; }
        public virtual DbSet<tblFuelStock> tblFuelStocks { get; set; }
        public virtual DbSet<tblFuelUnit> tblFuelUnits { get; set; }
    }
}
