//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CammsEngine
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFuelStock
    {
        public int ID { get; set; }
        public int FuelID { get; set; }
        public int MoveID { get; set; }
        public int Quantity { get; set; }
        public float UnitValue { get; set; }
        public string Description { get; set; }
        public System.DateTime MovementDate { get; set; }
    
        public virtual tblStockMovementType tblStockMovementType { get; set; }
    }
}
